- name: Configure Catalogue Service
  hosts: 172.31.88.7
  become: yes
  tasks:
    - name: Disable default NodeJS module
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Enable NodeJS 20 module
      ansible.builtin.shell: dnf module enable nodejs:20 -y

    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Add roboshop user
      ansible.builtin.user:
        name: roboshop
        create_home: yes

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download catalogue application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip

    - name: Unzip application
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install Node.js dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app

    - name: Copy catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes

    - name: Setup MongoDB repo
      ansible.builtin.copy:
        content: |
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://pgp.mongodb.com/server-7.0.asc
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Install MongoDB shell
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: Load MongoDB schema
      ansible.builtin.shell: mongosh --host 172.31.89.109 </app/schema/catalogue.js
