- name: Configure Catalogue service
  hosts: 172.31.88.7
  become: yes
  tasks:
    - name: Disable Default Nodejs & Enable Nodejs 20
      ansible.builtin.shell: |
        dnf module disable nodejs -y
        dnf module enable nodejs:20 -y
    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present 
    - name: Add roboshop user
      ansible.builtin.user:
        name: roboshop
        create_home: yes
    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: Download catalogue application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp
    - name: Unzip application files in tmp directory
      ansible.builtin.unarchive:
        src:  /tmp/catalogue.zip
        dest: /app
        remote_src: yes
    - name: Install Node.js dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app
    - name: Copy catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service
    - name: Daemon Reload and Starting
      ansible.builtin.service:
        daemon_reload: true
    - name: Start and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes
    - name: Copy mongodb repo
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo
    - name: Load MongoDB Schema
      ansible.builtin.shell: mongosh --host 172.31.89.109 </app/schema/catalogue.js
      
