- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: Disable old Node.js and enable Node.js 20
      ansible.builtin.shell: |
        dnf module disable nodejs -y
        dnf module enable nodejs:20 -y

    - name: Install Node.js 20
      ansible.builtin.dnf:
        name: nodejs
        state: present
